/// Flutter icons CustomHome
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomHome
///      fonts:
///       - asset: fonts/CustomHome.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class CustomHome {
  CustomHome._();

  static const _kFontFam = 'CustomHome';
  static const String? _kFontPkg = null;

  static const IconData location = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData access_time = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData people = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
